/**
 * Seedling Publisher — Git output pipeline + TOKENS.md generator
 *
 * Responsibilities:
 * 1. Watch /workspace/output for new artifacts from agent containers
 * 2. Validate artifacts (non-empty, proper format, no secrets)
 * 3. Batch-commit validated artifacts to the public GitHub repo
 * 4. Scrape Bifrost /metrics endpoint for token usage data
 * 5. Generate/update TOKENS.md from cumulative usage
 * 6. Single point of GitHub auth (no per-agent PAT sprawl)
 *
 * Environment:
 *   GITHUB_TOKEN          — PAT with repo write access
 *   GITHUB_REPO           — owner/repo (e.g., dschirmer-shiftkey/komatik-yggdrasil)
 *   GITHUB_BRANCH         — target branch (default: main)
 *   SEEDLING_NAME         — human name for commit messages (e.g., "Energy")
 *   SEEDLING_DIR          — path within repo (e.g., seedlings/001-energy)
 *   BIFROST_METRICS_URL   — Bifrost Prometheus metrics endpoint
 *   PUBLISH_INTERVAL_MINUTES — how often to check for new outputs (default: 30)
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { Pool } from "pg";

const OUTPUT_DIR = "/workspace/output";
const INTERVAL_MS = (parseInt(process.env.PUBLISH_INTERVAL_MINUTES || "30", 10)) * 60 * 1000;
const SEEDLING_NAME = process.env.SEEDLING_NAME || "Unknown Seedling";
const SEEDLING_DIR = process.env.SEEDLING_DIR || "seedlings/unknown";
const BIFROST_METRICS_URL = process.env.BIFROST_METRICS_URL || "http://bifrost:8080/metrics";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

function getNewArtifacts() {
  if (!fs.existsSync(OUTPUT_DIR)) return [];
  return fs.readdirSync(OUTPUT_DIR, { recursive: true })
    .filter((f) => !f.startsWith("."))
    .map((f) => path.join(OUTPUT_DIR, f))
    .filter((f) => fs.statSync(f).isFile());
}

function validateArtifact(filePath) {
  const content = fs.readFileSync(filePath, "utf-8");
  if (content.trim().length === 0) return { valid: false, reason: "empty file" };
  const secretPatterns = [/sk-[a-zA-Z0-9]{20,}/, /ghp_[a-zA-Z0-9]{36}/, /AKIA[A-Z0-9]{16}/];
  for (const pattern of secretPatterns) {
    if (pattern.test(content)) return { valid: false, reason: "possible secret detected" };
  }
  return { valid: true };
}

async function fetchTokenUsage() {
  try {
    const res = await fetch(BIFROST_METRICS_URL);
    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  }
}

async function getDbTokenSummary() {
  const result = await pool.query(`
    SELECT
      provider,
      model,
      COUNT(*) as calls,
      SUM(input_tokens) as total_input_tokens,
      SUM(output_tokens) as total_output_tokens,
      SUM(cost_usd) as total_cost_usd
    FROM llm_usage
    GROUP BY provider, model
    ORDER BY total_cost_usd DESC
  `);
  return result.rows;
}

function generateTokensMd(usage) {
  const now = new Date().toISOString().split("T")[0];
  const totalCost = usage.reduce((sum, r) => sum + parseFloat(r.total_cost_usd || 0), 0);
  const totalTokens = usage.reduce((sum, r) => sum + parseInt(r.total_input_tokens || 0) + parseInt(r.total_output_tokens || 0), 0);

  let md = `# TOKENS.md — ${SEEDLING_NAME} Compute Ledger\n\n`;
  md += `> Last updated: ${now}\n`;
  md += `> All compute donated by Komatik under the Pledge 1% Compute commitment.\n\n`;
  md += `## Summary\n\n`;
  md += `- **Total tokens**: ${totalTokens.toLocaleString()}\n`;
  md += `- **Total cost**: $${totalCost.toFixed(4)}\n`;
  md += `- **LLM calls**: ${usage.reduce((sum, r) => sum + parseInt(r.calls || 0), 0).toLocaleString()}\n\n`;
  md += `## Breakdown by Model\n\n`;
  md += `| Provider | Model | Calls | Input Tokens | Output Tokens | Cost (USD) |\n`;
  md += `|----------|-------|-------|-------------|--------------|------------|\n`;

  for (const row of usage) {
    md += `| ${row.provider} | ${row.model} | ${parseInt(row.calls).toLocaleString()} `;
    md += `| ${parseInt(row.total_input_tokens || 0).toLocaleString()} `;
    md += `| ${parseInt(row.total_output_tokens || 0).toLocaleString()} `;
    md += `| $${parseFloat(row.total_cost_usd || 0).toFixed(4)} |\n`;
  }

  md += `\n---\n*Auto-generated by the Seedling Publisher service from Bifrost metrics.*\n`;
  return md;
}

async function publishCycle() {
  console.log(`[publisher] Checking for new artifacts...`);

  const artifacts = getNewArtifacts();
  if (artifacts.length === 0) {
    console.log(`[publisher] No new artifacts`);
  } else {
    console.log(`[publisher] Found ${artifacts.length} artifacts`);
    for (const artifact of artifacts) {
      const result = validateArtifact(artifact);
      if (result.valid) {
        console.log(`[publisher] Valid: ${path.basename(artifact)}`);
      } else {
        console.warn(`[publisher] Rejected ${path.basename(artifact)}: ${result.reason}`);
      }
    }
    // TODO: git add, commit, push validated artifacts to GITHUB_REPO
    // Uses GITHUB_TOKEN for auth. Commits go to SEEDLING_DIR within the repo.
  }

  const usage = await getDbTokenSummary();
  if (usage.length > 0) {
    const tokensMd = generateTokensMd(usage);
    const tokensPath = path.join(OUTPUT_DIR, "TOKENS.md");
    fs.writeFileSync(tokensPath, tokensMd);
    console.log(`[publisher] Updated TOKENS.md (${usage.length} model entries)`);
  }
}

async function main() {
  console.log(`[publisher] Starting for ${SEEDLING_NAME} (${SEEDLING_DIR})`);
  console.log(`[publisher] Publish interval: ${INTERVAL_MS / 60000} minutes`);

  await publishCycle();

  setInterval(publishCycle, INTERVAL_MS);

  process.on("SIGTERM", async () => {
    console.log("[publisher] Shutting down...");
    await pool.end();
    process.exit(0);
  });
}

main().catch((err) => {
  console.error("[publisher] Fatal error:", err);
  process.exit(1);
});
